global:
  evaluation_interval: 30s
  scrape_interval: 20s
  external_labels:
    prometheus: monitoring/k8s
    prometheus_replica: prometheus-k8s-0
rule_files:
- /etc/prometheus/rules/prometheus-k8s-rulefiles-0/*.yaml
scrape_configs:

- job_name: 'masa-gatekeeper'
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /manager/prometheus
  honor_timestamps: true
  scheme: http
  basic_auth:
    username: keeper
    password: keeperhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDL8
  static_configs:
  - targets:
    - 172.21.102.143:8099
    labels:
      __address__: 172.21.102.143:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.102.143:8099
      application: masa-gatekeeper
  - targets:
    - 172.21.181.142:8099
    labels:
      __address__: 172.21.181.142:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.181.142:8099
      application: masa-gatekeeper
  - targets:
    - 172.21.181.143:8099
    labels:
      __address__: 172.21.181.143:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.181.143:8099
      application: masa-gatekeeper
  - targets:
    - 172.21.181.144:8099
    labels:
      __address__: 172.21.181.144:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.181.144:8099
      application: masa-gatekeeper
  - targets:
    - 172.21.181.145:8099
    labels:
      __address__: 172.21.181.145:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.181.145:8099
      application: masa-gatekeeper


- job_name: 'masa-meshkeeper'
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /manager/prometheus
  honor_timestamps: true
  scheme: http
  basic_auth:
    username: keeper
    password: keeperhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDL8
  static_configs:
  - targets:
    - 172.21.194.44:8099
    labels:
      __address__: 172.21.194.44:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.194.44:8099
      application: masa-meshkeeper
  - targets:
    - 172.21.194.6:8099
    labels:
      __address__: 172.21.194.6:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.194.6:8099
      application: masa-meshkeeper
  - targets:
    - 172.21.194.41:8099
    labels:
      __address__: 172.21.194.41:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.194.41:8099
      application: masa-meshkeeper
  - targets:
    - 172.21.194.7:8099
    labels:
      __address__: 172.21.194.7:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.194.7:8099
      application: masa-meshkeeper
  - targets:
    - 172.21.194.26:8099
    labels:
      __address__: 172.21.194.26:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.194.26:8099
      application: masa-meshkeeper
  - targets:
    - 172.21.194.21:8099
    labels:
      __address__: 172.21.194.21:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.194.21:8099
      application: masa-meshkeeper
  - targets:
    - 172.21.194.17:8099
    labels:
      __address__: 172.21.194.17:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.194.17:8099
      application: masa-meshkeeper
  - targets:
    - 172.21.194.4:8099
    labels:
      __address__: 172.21.194.4:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.194.4:8099
      application: masa-meshkeeper

- job_name: 'masa-keeper'
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /manager/prometheus
  honor_timestamps: true
  scheme: http
  basic_auth:
    username: keeper
    password: keeperhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDL8
  static_configs:
  - targets:
    - 172.21.16.7:8099
    labels:
      __address__: 172.21.16.7:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.16.7:8099
      application: masa-keeper
  - targets:
    - 10.108.128.29:8099
    labels:
      __address__: 10.108.128.29:8099
      __metrics_path__: /manager/prometheus
      instance: 10.108.128.29:8099
      application: masa-keeper
  - targets:
    - 172.21.2.10:8099
    labels:
      __address__: 172.21.2.10:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.2.10:8099
      application: masa-keeper
  - targets:
    - 172.21.16.103:8099
    labels:
      __address__: 172.21.16.103:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.16.103:8099
      application: masa-keeper
  - targets:
    - 172.21.8.36:8199
    labels:
      __address__: 172.21.8.36:8199
      __metrics_path__: /manager/prometheus
      instance: 172.21.8.36:8199
      application: masa-keeper
  - targets:
    - 172.21.8.41:8099
    labels:
      __address__: 172.21.8.41:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.8.41:8099
      application: masa-keeper
  - targets:
    - 172.21.194.10:8099
    labels:
      __address__: 172.21.194.10:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.194.10:8099
      application: masa-keeper
  - targets:
    - 172.21.194.4:8099
    labels:
      __address__: 172.21.194.4:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.194.4:8099
      application: masa-keeper
  - targets:
    - 172.21.194.43:8099
    labels:
      __address__: 172.21.194.43:8099
      __metrics_path__: /manager/prometheus
      instance: 172.21.194.43:8099
      application: masa-keeper


- job_name: 'masa-adminserver'
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /adminserver/actuator/prometheus 
  honor_timestamps: true
  scheme: http
  basic_auth:
    username: admserver
    password: admserverl2wY9e5pcDZAtIVMfeFM1TQG4Eu7r98F0VpH
  static_configs:
  - targets:
    - 172.21.0.171:5712
    labels:
      __address__: 172.21.0.171:5712
      __metrics_path__: /adminserver/actuator/prometheus 
      instance: 172.21.0.171:5712
      application: masa-adminserver
  - targets:
    - 172.21.0.188:5712
    labels:
      __address__: 172.21.0.188:5712
      __metrics_path__: /adminserver/actuator/prometheus
      instance: 172.21.0.188:5712
      application: masa-adminserver
  - targets:
    - 172.21.1.36:5712
    labels:
      __address__: 172.21.1.36:5712
      __metrics_path__: /adminserver/actuator/prometheus
      instance: 172.21.1.36:5712
      application: masa-adminserver

- job_name: 'masa-conf'
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /nacos/actuator/prometheus
  honor_timestamps: true
  scheme: http
  basic_auth:
    username: registry
    password: registryTeAxMQN2BmyoJhEBimvgpXfMb38pBiueRMiJ
  static_configs:
  - targets:
    - 172.21.1.36:5531
    labels:
      __address__: 172.21.1.36:5531
      __metrics_path__: /nacos/actuator/prometheus
      instance: 172.21.1.36:5531
      application: masa-conf
  - targets:
    - 172.21.0.188:5531
    labels:
      __address__: 172.21.0.188:5531
      __metrics_path__: /nacos/actuator/prometheus
      instance: 172.21.0.188:5531
      application: masa-conf
  - targets:
    - 172.21.0.171:5531
    labels:
      __address__: 172.21.0.171:5531
      __metrics_path__: /nacos/actuator/prometheus
      instance: 172.21.0.171:5531
      application: masa-conf

- job_name: 'masa-registry'
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /nacos/actuator/prometheus
  honor_timestamps: true
  scheme: http
  basic_auth:
    username: registry
    password: registryTeAxMQN2BmyoJhEBimvgpXfMb38pBiueRMiJ
  static_configs:
  - targets:
    - 172.21.70.12:5529
    labels:
      __address__: 172.21.70.12:5529
      __metrics_path__: /nacos/actuator/prometheus
      instance: 172.21.70.12:5529
      application: masa-registry
  - targets:
    - 172.21.70.11:5529
    labels:
      __address__: 172.21.70.11:5529
      __metrics_path__: /nacos/actuator/prometheus
      instance: 172.21.70.11:5529
      application: masa-registry
  - targets:
    - 172.21.68.226:5529
    labels:
      __address__: 172.21.68.226:5529
      __metrics_path__: /nacos/actuator/prometheus
      instance: 172.21.68.226:5529
      application: masa-registry

- job_name: 'gns_general_pressure_redis_cluster_datastore'
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /prometheus
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets:
    - 10.108.193.40:30311
    labels:
      __address__: 10.108.193.40:30311
      __metrics_path__: /prometheus
      instance: 10.108.193.40:30311
      cluster: GNS_GENERAL_PRESSURE_REDIS_CLUSTER_DATASTORE

- job_name: 'ccpd_cs_redis_cluster_cache'
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /prometheus
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets:
    - 10.107.97.16:30301
    labels:
      __address__: 10.107.97.16:30301
      __metrics_path__: /prometheus
      instance: 10.107.97.16:30301
      cluster: CCPD_CS_REDIS_CLUSTER_CACHE
  - targets:
    - 10.107.97.231:30301
    labels:
      __address__: 10.107.97.231:30301
      __metrics_path__: /prometheus
      instance: 10.107.97.231:30301
      cluster: CCPD_CS_REDIS_CLUSTER_CACHE
  - targets:
    - 10.107.97.177:30301
    labels:
      __address__: 10.107.97.177:30301
      __metrics_path__: /prometheus
      instance: 10.107.97.177:30301
      cluster: CCPD_CS_REDIS_CLUSTER_CACHE

- job_name: 'cfpd_u_redis_cluster_cache'
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /prometheus
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets:
    - 10.108.193.160:30301
    labels:
      __address__: 10.108.193.160:30301
      __metrics_path__: /prometheus
      instance: 10.108.193.160:30301
      cluster: CFPD_U_REDIS_CLUSTER_CACHE
  - targets:
    - 10.108.192.47:30301
    labels:
      __address__: 10.108.192.47:30301
      __metrics_path__: /prometheus
      instance: 10.108.192.47:30301
      cluster: CFPD_U_REDIS_CLUSTER_CACHE
  - targets:
    - 10.108.193.40:30301
    labels:
      __address__: 10.108.193.40:30301
      __metrics_path__: /prometheus
      instance: 10.108.193.40:30301
      cluster: CFPD_U_REDIS_CLUSTER_CACHE

- job_name: 'PPD_DMZ_REDIS_CLUSTER_CACHE_PROXY'
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /prometheus
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets:
    - 10.107.98.232:20101
    labels:
      __address__: 10.107.98.232:20101
      __metrics_path__: /prometheus
      instance: 10.107.98.232:20101
      cluster: PPD_DMZ_REDIS_CLUSTER_CACHE
  - targets:
    - 10.107.98.16:20101
    labels:
      __address__: 10.107.98.16:20101
      __metrics_path__: /prometheus
      instance: 10.107.98.16:20101
      cluster: PPD_DMZ_REDIS_CLUSTER_CACHE
  - targets:
    - 10.107.98.128:20101
    labels:
      __address__: 10.107.98.128:20101
      __metrics_path__: /prometheus
      instance: 10.107.98.128:20101
      cluster: PPD_DMZ_REDIS_CLUSTER_CACHE


- job_name: 'ispd_bas_redis_cluster_cache'
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /prometheus
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets:
    - 10.108.192.60:30301
    labels:
      __address__: 10.108.192.60:30301
      __metrics_path__: /prometheus
      instance: 10.108.192.60:30301
      cluster: ISPD_BAS_REDIS_CLUSTER_CACHE
  - targets:
    - 10.108.193.64:30301
    labels:
      __address__: 10.108.193.64:30301
      __metrics_path__: /prometheus
      instance: 10.108.193.64:30301
      cluster: ISPD_BAS_REDIS_CLUSTER_CACHE
  - targets:
    - 10.108.192.99:30301
    labels:
      __address__: 10.108.192.99:30301
      __metrics_path__: /prometheus
      instance: 10.108.192.99:30301
      cluster: ISPD_BAS_REDIS_CLUSTER_CACHE

- job_name: 'ispd_v_redis_cluster_cache'
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /prometheus
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets:
    - 10.108.193.153:30301
    labels:
      __address__: 10.108.193.153:30301
      __metrics_path__: /prometheus
      instance: 10.108.193.153:30301
      cluster: ISPD_V_REDIS_CLUSTER_CACHE
  - targets:
    - 10.108.192.223:30301
    labels:
      __address__: 10.108.192.223:30301
      __metrics_path__: /prometheus
      instance: 10.108.192.223:30301
      cluster: ISPD_V_REDIS_CLUSTER_CACHE
  - targets:
    - 10.108.192.184:30301
    labels:
      __address__: 10.108.192.184:30301
      __metrics_path__: /prometheus
      instance: 10.108.192.184:30301
      cluster: ISPD_V_REDIS_CLUSTER_CACHE
  - targets:
    - 10.108.193.65:30301
    labels:
      __address__: 10.108.193.65:30301
      __metrics_path__: /prometheus
      instance: 10.108.193.65:30301
      cluster: ISPD_V_REDIS_CLUSTER_CACHE
  - targets:
    - 10.108.192.85:30301
    labels:
      __address__: 10.108.192.85:30301
      __metrics_path__: /prometheus
      instance: 10.108.192.85:30301
      cluster: ISPD_V_REDIS_CLUSTER_CACHE
  - targets:
    - 10.108.192.73:30301
    labels:
      __address__: 10.108.192.73:30301
      __metrics_path__: /prometheus
      instance: 10.108.192.73:30301
      cluster: ISPD_V_REDIS_CLUSTER_CACHE

- job_name: 'dbpd_rtqs_cloud_redis_cluster_cache'
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /prometheus
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets:
    - 172.21.8.186:30331
    labels:
      __address__: 172.21.8.186:30331
      __metrics_path__: /prometheus
      instance: 172.21.8.186:30331
      cluster: DBPD_RTQS_CLOUD_REDIS_CLUSTER_CACHE
  - targets:
    - 172.21.8.178:30331
    labels:
      __address__: 172.21.8.178:30331
      __metrics_path__: /prometheus
      instance: 172.21.8.178:30331
      cluster: DBPD_RTQS_CLOUD_REDIS_CLUSTER_CACHE
  - targets:
    - 172.21.9.9:30331
    labels:
      __address__: 172.21.9.9:30331
      __metrics_path__: /prometheus
      instance: 172.21.9.9:30331
      cluster: DBPD_RTQS_CLOUD_REDIS_CLUSTER_CACHE


- job_name: 'loki_test'
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets:
    - 172.21.88.59:3100
    labels:
      __address__: 172.21.88.59:3100
      __metrics_path__: /metrics
      instance: 172.21.88.59:3100
      cluster: LOKI_CLUSTER

- job_name: 'loki_scrape'
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets:
    - 172.21.9.16:3100
    labels:
      ip_address: 172.21.9.16
      __address__: 172.21.9.16:3100
      __metrics_path__: /metrics
      instance: 172.21.9.16:3100
  #- targets:
  #  - 172.21.9.106:3100
  #  labels:
  #    ip_address: 172.21.9.106
  #    __address__: 172.21.9.106:3100
  #    __metrics_path__: /metrics
  #    instance: 172.21.9.106:3100
  #- targets:
  #  - 172.21.1.116:3100
  #  labels:
  #    ip_address: 172.21.1.116
  #    __address__: 172.21.1.116:3100
  #    __metrics_path__: /metrics
  #    instance: 172.21.1.116:3100
  #- targets:
  #  - 172.21.1.74:3100
  #  labels:
     # ip_address: 172.21.1.74
     # __address__: 172.21.1.74:3100
     # __metrics_path__: /metrics
     # instance: 172.21.1.74:3100
  #- targets:
  #  - 172.21.8.42:3100
  #  labels:
  #    ip_address: 172.21.8.42
  #    __address__: 172.21.8.42:3100
  #    __metrics_path__: /metrics
  #    instance: 172.21.8.42:3100


- job_name: ISPD_BAS_REDIS_CLUSTER_CACHE
  metrics_path: '/assemble'
  static_configs:
  - targets: ['10.108.193.64:19997']
  relabel_configs:
  - source_labels: [job]
    target_label: __param_clusterName

- job_name: ISPD_V_REDIS_CLUSTER_CACHE
  metrics_path: '/assemble'
  static_configs:
  - targets: ['10.108.193.153:19997']
  relabel_configs:
  - source_labels: [job]
    target_label: __param_clusterName

- job_name: PPD_MGMT_REDIS_CLUSTER_CACHE
  metrics_path: '/assemble'
  static_configs:
  - targets: ['10.107.98.239:19997']
  relabel_configs:
  - source_labels: [job]
    target_label: __param_clusterName

- job_name: CCPD_CS_REDIS_CLUSTER_CACHE
  metrics_path: '/assemble'
  static_configs:
  - targets: ['10.107.97.231:19997']
  relabel_configs:
  - source_labels: [job]
    target_label: __param_clusterName

#- job_name: GNS_GENERAL_PRESSURE_REDIS_CLUSTER_DATASTORE
#  metrics_path: '/assemble'
#  static_configs:
#  - targets: ['10.108.193.160:19997']
#  relabel_configs:
#  - source_labels: [job]
#    target_label: __param_clusterName

- job_name: CFPD_U_REDIS_CLUSTER_CACHE
  metrics_path: '/assemble'
  static_configs:
  - targets: ['10.108.193.160:19997']
  relabel_configs:
  - source_labels: [job]
    target_label: __param_clusterName

- job_name: CFPD_REDIS_CLUSTER_CACHE
  metrics_path: '/assemble'
  static_configs:
  - targets: ['10.107.97.120:19997']
  relabel_configs:
  - source_labels: [job]
    target_label: __param_clusterName

- job_name: RPD_GENERAL_REDIS_CLUSTER_CACHE
  metrics_path: '/assemble'
  static_configs:
  - targets: ['10.107.98.232:19997']
  relabel_configs:
  - source_labels: [job]
    target_label: __param_clusterName

- job_name: GNS_U_3.0_REDIS_CLUSTER_DATASTORE
  metrics_path: '/assemble'
  static_configs:
  - targets: ['10.107.118.151:19997']
  relabel_configs:
  - source_labels: [job]
    target_label: __param_clusterName

- job_name: GNS_GENERAL_PRESSURE_REDIS_CLUSTER_DATASTORE
  metrics_path: '/assemble'
  static_configs:
  - targets: ['10.108.193.40:19997']
  relabel_configs:
  - source_labels: [job]
    target_label: __param_clusterName

- job_name: 'kvrocks_exporter_targets'
  static_configs:
  - targets:
    - kvrocks://10.107.118.74:6666
    - kvrocks://10.107.108.205:6666
  metrics_path: /scrape
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: 10.107.108.205:9121

remote_write:
  # - url: "http://prometheus-kafka-adapter.masa-prometheus.svc.cluster.local:8080/receive"
  #- url: "http://172.21.1.74:8091/receive"
  #- url: "http://10.107.108.254:8091/receive"
  # - url: "http://10.108.193.86:3001/receive"
  #- url: "http://172.21.1.74:8092/receive"
alerting:
  alert_relabel_configs:
  - action: labeldrop
    regex: prometheus_replica
  alertmanagers:
  - path_prefix: /
    scheme: http
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - masa-prometheus
    relabel_configs:
    - action: keep
      source_labels:
      - __meta_kubernetes_service_name
      regex: alertmanager-sts-svc
    - action: keep
      source_labels:
      - __meta_kubernetes_endpoint_port_name
      regex: web
